version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flutterpos
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: dev
    image: flutterpos-api:dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/flutterpos
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules

volumes:
  pgdata:
  api_node_modules:

